"""Discogs sync package — re-exports all public symbols for ``discogs_sync`` shim."""
from __future__ import annotations

from ._db import (
    ART_DIR,
    DATA_DIR,
    DB_PATH,
    DDL,
    PI_DIR,
    REPO_ROOT,
    _migrate_schema,
    log,
    now_iso,
    open_db,
)
from ._enrich import (
    _AMBIGUOUS_TITLE,
    _apply_recording_level_fallback,
    _build_title_duration_map,
    _build_title_recording_mbid_map,
    _enrich_durations_from_musicbrainz_async,
    _fill_null_durations_by_title,
    _is_better_candidate,
    _is_perfect_candidate,
    _maybe_enrich_durations,
    _norm_title,
    _resolve_best_matching_mbid,
    _resolve_mbid_if_needed,
    _score_candidate,
    _warn_if_large_count_diff,
)
from ._helpers import (
    SIDE_RE,
    _get,
    _parse_discogs_duration,
    iter_leaf_tracks,
    join_artists,
    join_formats,
    join_labels,
    parse_duration,
    position_to_side,
    upsert_basic,
)
from ._passes import (
    USER_AGENT,
    fetch_art,
    fetch_detail,
    pass_art,
    pass_basic,
    pass_details,
    pass_enrich_durations,
)

__all__ = [
    # _db
    "ART_DIR",
    "DATA_DIR",
    "DB_PATH",
    "DDL",
    "PI_DIR",
    "REPO_ROOT",
    "_migrate_schema",
    "log",
    "now_iso",
    "open_db",
    # _enrich
    "_AMBIGUOUS_TITLE",
    "_apply_recording_level_fallback",
    "_build_title_duration_map",
    "_build_title_recording_mbid_map",
    "_enrich_durations_from_musicbrainz_async",
    "_fill_null_durations_by_title",
    "_is_better_candidate",
    "_is_perfect_candidate",
    "_maybe_enrich_durations",
    "_norm_title",
    "_resolve_best_matching_mbid",
    "_resolve_mbid_if_needed",
    "_score_candidate",
    "_warn_if_large_count_diff",
    # _helpers
    "SIDE_RE",
    "_get",
    "_parse_discogs_duration",
    "iter_leaf_tracks",
    "join_artists",
    "join_formats",
    "join_labels",
    "parse_duration",
    "position_to_side",
    "upsert_basic",
    # _passes
    "USER_AGENT",
    "fetch_art",
    "fetch_detail",
    "pass_art",
    "pass_basic",
    "pass_details",
    "pass_enrich_durations",
]
